# Generated by Django 4.0.5 on 2023-05-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='relative path to folder')),
                ('md5', models.CharField(max_length=32)),
                ('size', models.IntegerField()),
                ('update_datetime', models.DateTimeField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.folder')),
            ],
        ),
    ]
