# Generated by Django 4.0.5 on 2023-05-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('md5', models.CharField(max_length=32)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.folder')),
            ],
        ),
    ]
