# Generated by Django 4.0.5 on 2023-05-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_bucket_folder_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(unique=True)),
                ('current_id', models.IntegerField(default=0, verbose_name='Bigest synced id')),
                ('current_update_datetime', models.DateTimeField(null=True, verbose_name='newest updated datetime')),
                ('cnt', models.IntegerField(default=0)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file_manager.bucket')),
            ],
        ),
    ]
