# Generated by Django 4.0.5 on 2023-05-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_backup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='RootFolder',
        ),
    ]
