# Generated by Django 4.0.5 on 2023-05-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_rename_folder_rootfolder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Object',
        ),
    ]
