# Generated by Django 4.0.5 on 2023-05-21 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_rename_file_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='is_file',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='object',
            name='last_scan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
