# Generated by Django 4.0.5 on 2023-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_object_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='last_scan',
            field=models.DateTimeField(null=True),
        ),
    ]
