# Generated by Django 4.0.5 on 2023-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0010_backup_last_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='last_scan',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_scan',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
