# Generated by Django 4.2.5 on 2023-10-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0012_alter_object_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootfolder',
            old_name='path',
            new_name='windows_path',
        ),
    ]
