# Generated by Django 4.2.1 on 2023-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0013_rename_path_rootfolder_windows_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfolder',
            name='linux_path',
            field=models.FilePathField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rootfolder',
            name='windows_path',
            field=models.FilePathField(null=True, unique=True),
        ),
    ]
