# Generated by Django 4.2.5 on 2023-11-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_rootfolder_linux_path_alter_rootfolder_windows_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.object'),
        ),
    ]
