# Generated by Django 4.2.7 on 2023-11-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_rootfolder_linux_path_alter_rootfolder_windows_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current_update_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='newest updated datetime'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='path',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rootfolder',
            name='linux_path',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rootfolder',
            name='windows_path',
            field=models.TextField(null=True, unique=True),
        ),
    ]
