# Generated by Django 5.0 on 2024-01-01 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0015_alter_backup_current_update_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='last_scan',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='file_manager.object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='path',
            field=models.TextField(verbose_name='relative path to folder'),
        ),
        migrations.AlterField(
            model_name='rootfolder',
            name='linux_path',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rootfolder',
            name='windows_path',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
