# Generated by Django 5.0 on 2024-01-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0016_alter_backup_last_scan_alter_object_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_manager.object'),
        ),
    ]
