# Generated by Django 4.2.7 on 2024-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0018_object_level_object_lft_object_rght_object_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('folder', 'path')},
        ),
        migrations.AddField(
            model_name='object',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('folder', 'path'), ('parent', 'name')},
        ),
    ]
