# Generated by Django 4.2.7 on 2024-01-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0019_alter_object_unique_together_object_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='is_dir',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_file',
            field=models.BooleanField(),
        ),
    ]
