# Generated by Django 4.2.7 on 2024-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0020_alter_object_is_dir_alter_object_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
