# Generated by Django 4.2.7 on 2024-01-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0021_alter_object_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('update_parent', 'update_parent')], db_index=True)),
                ('level', models.IntegerField(default=0)),
                ('object_id', models.IntegerField(default=0)),
            ],
        ),
    ]
